import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { ChainTabs } from "@/components/chain-tabs";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interSans.variable} antialiased`} >
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger />
          <div className="flex flex-col">
            <div className="hidden md:flex flex-1 space-x-4 pl-8 ">
              <ChainTabs />
            </div>
            <div className="relative min-h-screen">
              {children}
            </div>
          </div>
        </SidebarProvider>

      </body>
    </html>
    // <html lang="en">
    // </html>
  );
}
